### ISSUE TITLE
Example mods?

### ISSUE THREAD

**Issue by turtiustrek** [MinecraftZenova/ZenovaLauncher#1]
Hello, i noticed that this a minecraft windows 10 edition launcher with a mod loader. I was not able to find any information around anything related to this project and wanting to know a bit more on how to use mods.
Thanks,

**Comment by ThePixelGamer** [comment]
Hi this project is still really early in development but if you want an example you can look here: [Zoom](https://github.com/MinecraftZenova/Zoom)
My own template can be found here: [Template](https://github.com/MinecraftZenova/Template)
Sorry for such a late response but I hope these help

**Comment by turtiustrek** [comment]
Ah thank you.
