### ISSUE TITLE
The app does not open

### ISSUE THREAD

**Issue by shizotoaster** [MinecraftZenova/ZenovaLauncher#17]
The app does not open for me. It shows Zenova logo for a couple of seconds and just closes then. Was tested on both win10 and win11 x64 with and without Administrator rights

**Comment by ThePixelGamer** [comment]
Hi sorry for the late response, it might be due to not having developer mode enabled?
But if you managed to install the app could you go to the directory you installed it to (if you chose the default it should be at ``%appdata%/zenova``) and upload the log there?
Might be good to delete the lines that start with Token near the top before uploading as that info isn't really relevant

**Comment by ThePixelGamer** [comment]
I was able to reproduce a crash on a vm but I'm not sure if it's the same issue but if the logs end after VersionDownload.standard it should be it.
Can you verify that you're logged into xbox and that in regedit this registry entry exists? ``Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\IdentityCRL\UserTileData``

**Comment by shizotoaster** [comment]
> Hi sorry for the late response, it might be due to not having developer mode enabled? But if you managed to install the app could you go to the directory you installed it to (if you chose the default it should be at `%appdata%/zenova`) and upload the log there? Might be good to delete the lines that start with Token near the top before uploading as that info isn't really relevant

https://pastebin.com/YfHh3AV3

**Comment by shizotoaster** [comment]
> I was able to reproduce a crash on a vm but I'm not sure if it's the same issue but if the logs end after VersionDownload.standard it should be it. Can you verify that you're logged into xbox and that in regedit this registry entry exists? `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\IdentityCRL\UserTileData`

I am logged in my Microsoft account in Microsoft store, is this enough?

Here's my regedit, this entry exists
![изображение](https://user-images.githubusercontent.com/51480483/173196170-efc2306e-eec0-435e-ac73-c235b718023f.png)

**Comment by ThePixelGamer** [comment]
With how the launcher is currently designed it expects your account to be logged into the xbox app, I'm gonna change this when I get the chance but for now that's all that needs to be done and it should start running

**Comment by shizotoaster** [comment]
Have tried launching it with XBOX app opened (I am logged in my account), still nothing, just shows the Zenova logo and disappears then

**Comment by ThePixelGamer** [comment]
The PR should fix the issue entirely but can you verify that the xbox app shows this in the top left? 
![image](https://user-images.githubusercontent.com/15077848/173239460-330a5608-324d-4a68-901f-279f1a153a74.png)
and that the ``Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\XboxLive`` registry entry contains one of the Gamertag entries?

**Comment by ThePixelGamer** [comment]
Actually thinking about it you might not have the Gamertag entry we use and instead it's putting it into one of the modern entries (which isn't really properly handled yet)

**Comment by shizotoaster** [comment]
Everything seem to be fine with the account
![изображение](https://user-images.githubusercontent.com/51480483/173245870-8a835706-5fd1-430d-a5a4-6f88c98324db.png)
![изображение](https://user-images.githubusercontent.com/51480483/173245883-f612b94a-d0d4-4e48-96ba-78968ec1d1a0.png)

**Comment by ThePixelGamer** [comment]
Wait sorry I didn't read your log right, it's showing that the ModManager ctor isn't getting finished

**Comment by shizotoaster** [comment]
So, what's the solution then?

**Comment by ThePixelGamer** [comment]
Can you screenshot your folder directory and open the mod folder's properties? I need to see a screenshot of what security groups are on the folder. (I'm also gonna delete the registry screenshot simply to hide the sensitive info)

**Comment by ThePixelGamer** [comment]
We determined on discord that the issue was in regards to how we set ALL APPLICATION PACKAGES
